// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  topCommandList = 1,
  CommandWord = 3,
  Word = 4,
  Escaped = 7,
  SQuoteChars = 9,
  EscapedSQuote = 10,
  DQuotedChar = 12,
  EscapedDQuote = 13,
  Redirect = 14,
  RedirectOp = 15,
  CommandList = 21,
  Elif = 23,
  Else = 25,
  PipeOp = 29,
  LogicOp = 31,
  Separator = 32
