/*
 * WARNING: DO NOT EDIT!
 * This file is automatically generated from Pixmap_CH__T__Template.java by turtleduck.bitmap.BitmapGenerator
 */

package turtleduck.bitmap;

import org.joml.Vector4i; 

/**
 * Interface for byte-pixmaps with 4 colour channels. 
 * 
 * A pixmap is a two-dimensional grid of pixels, with each pixel having one or
 * more colour components (“channels”). This interface provides generic
 * {@link #get(int, int, int)} and {@link #set(int, int, int, byte)} methods
 * to read or write from arbitrary channels, as well as specific methods for
 * accessing a single channel/colour component.
 * 
 * For global operations, you can iterate over all pixel locations with
 * {@link #foreachLocation(turtleduck.bitmap.BytePixmap.LocationConsumer)},
 * and each pixel value with {@link #foreach(PixelConsumer4T)} or
 * {@link #map(PixelFunction4T)}.
 * 
 * @author anya
 *
 */
public interface Pixmap4b extends BytePixmap {

    /**
     * @return Number of channels (values per pixel) of the pixmap (always 4 for Pixmap4b).
     */
    int channels();

    /**
     * Read the value of a component at (x,y)
     * 
     * @param x  X coordinate
     * @param y  Y coordinate
     * @param ch The channel (0–3) 
     * @return The value of channel ch at (x,y)
     */
    byte get(int x, int y, int ch);

    /**
     * Read the value of the channel 0 (red) component 
     * 
     * 
     * @param x X coordinate 
     * @param y Y coordinate 
     * @return The value at (x,y) 
     */
    byte r(int x, int y); 

    /**
     * Read the value of the channel 1 (green) component 
     * 
     * 
     * @param x X coordinate 
     * @param y Y coordinate 
     * @return The value at (x,y) 
     */
    byte g(int x, int y); 

    /**
     * Read the value of the channel 2 (blue) component 
     * 
     * 
     * @param x X coordinate 
     * @param y Y coordinate 
     * @return The value at (x,y) 
     */
    byte b(int x, int y); 

    /**
     * Read the value of the channel 3 (alpha) component 
     * 
     * 
     * @param x X coordinate 
     * @param y Y coordinate 
     * @return The value at (x,y) 
     */
    byte a(int x, int y); 

    /**
     * Set the value of a channel at (x,y)
     * 
     * @param x     X coordinate
     * @param y     Y coordinate
     * @param ch    The channel (0–3) 
     * @param value The new value for (x,y)
     */
    Pixmap4b set(int x, int y, int ch, byte value);

    /**
     * Set the value of the channel 0 (red) component 
     * 
     * 
     * @param x     X coordinate 
     * @param y     Y coordinate 
     * @param value The new red value for (x,y) 
     */
    Pixmap4b r(int x, int y, byte value); 

    /**
     * Set the value of the channel 0 (red) component 
     * 
     * 
     * @param x     X coordinate 
     * @param y     Y coordinate 
     * @param value The new red value for (x,y) 
     */
    Pixmap4b g(int x, int y, byte value); 

    /**
     * Set the value of the channel 0 (red) component 
     * 
     * 
     * @param x     X coordinate 
     * @param y     Y coordinate 
     * @param value The new red value for (x,y) 
     */
    Pixmap4b b(int x, int y, byte value); 

    /**
     * Set the value of the channel 0 (red) component 
     * 
     * 
     * @param x     X coordinate 
     * @param y     Y coordinate 
     * @param value The new alpha value for (x,y) 
     */
    Pixmap4b a(int x, int y, byte value); 

    /**
     * Do something for each location in the bitmap
     * 
     * @param consumer A consumer, will receive (this bitmap, x, y)
     */
    Pixmap4b foreachLocation(LocationConsumer consumer);

    /**
     * Do something for each value in the bitmap
     * 
     * @param consumer A consumer, will receive (r,g,b,a) 
     */
    Pixmap4b foreach(PixelConsumer4b consumer);
    Pixmap4b foreach(PixelConsumerb consumer);

    /**
     * Transform each value in the bitmap.
     * 
     * @param fun A function
     */
    Pixmap4b map(PixelFunction4b fun);

    public interface PixelFunction4b { 
        Vector4i apply(Vector4i p);
    }


    public interface PixelConsumer4b {
        void accept(int x, int y //
                , byte r 
                , byte g 
                , byte b 
                , byte a 
        );
    }

}
